### ISSUE TITLE
Booting from second ZController SDCARD

### ISSUE THREAD

**Issue by Caasper911** [nihirash/karabas-pro-cpm#6]
If booting from the first SDCARD fails (CS bit 1 active LOW), let's try booting from the second SDCARD (CS bit 3 active HIGH, as in tsconf sources).

**Comment by nihirash** [comment]
I've tried implement it in commit  https://github.com/nihirash/karabas-pro-cpm/pull/5/commits/1af823a31a1ef3416376b1f61d59d42b62e78b1a
